### ISSUE TITLE
Question: Does Bump support multiple release channels? 

### ISSUE THREAD

**Issue by armadsen** [replay-software/bump#1]
Bump looks really great, thanks! Does bump support multiple release channels, e.g. beta, and release?

More context: My current solution (which is getting creaky) for update distribution, appcast generation, etc., supports multiple release channels, e.g. development, beta, release. I can release beta updates that only those users who have opted in to beta updates will see. When a build is ready for non-beta release, I can promote it to the release channel. All three channels have their own appcast, and the app just uses the right one depending on whether the user has enabled beta updates.

**Comment by almonk** [comment]
Bump doesn't support multiple release channels natively, but this is a really interesting feature we could look to add. In the meantime, you could approach this simply by having a separate Bump repo per release channel (e.g. `app-stable`, `app-beta`), which would give you separate changelog URLS and S3 buckets.

**Comment by armadsen** [comment]
Thanks for the great answer! I'll do the separate repo thing for now, but built in support for multiple release channels would be cool at some point.
