### ISSUE TITLE
Sparkle v2 Support

### ISSUE THREAD

**Issue by sktusing** [replay-software/bump#2]
Hello,

I am curious if this will eventually support Sparkle v2.2, and multiple release channels.

Thanks!

**Comment by almonk** [comment]
@sktusing Bump currently supports some core features of Sparkle 2.x, however as you said, we don't support multiple release channels yet as we've never needed this ourselves. I've noted this as a feature request to be considered the next time we're working on roadmap. Thanks for sharing!
