### ISSUE TITLE
Still not tested with Sparkle 2.x?

### ISSUE THREAD

**Issue by brduffy** [replay-software/bump#3]
Sparkle 2.x has been out for a while. I really want to use Bump in my project but I'm hesitant to start with an old version of Sparkle. If I don't hear anything I guess I'll just try it with 2.x, see what happens and report back.

**Comment by almonk** [comment]
We actually use Bump in production with Sparkle 2 so it's safe to say it has been working ok for us, although as noted in the readme, Bump does not support all features.
